import Head from "next/head";
import Headers from "../home/Headers";
import Footer from "../home/Footer";

export default function Layout({ children }) {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>PORTFOLIO AMAN :)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Headers />
      <main className="flex-1 bg-gray-100 p-4">{children}</main>
      <Footer />
    </div>
  );
}
